Repository jumpserver/lina, pull requests merged in 2022-09, with the labels that each got.

#2013 feat: 云同步支持资产同步腾讯云(轻量应用服务器)
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/Cloud/Account/AccountList.vue
  src/views/assets/Cloud/const.js
Labels: 类型:新功能

#2016 feat: feat: 支持连接开启了ssl的Redis数据库
  src/views/applications/DatabaseApp/const.js
Labels: 类型:新功能

#2018 feat: 支持OAuth2协议自定义注销功能
  src/views/settings/Auth/OAuth2.vue
Labels: 类型:新功能

#2025 feat: 云同步支持同步天翼私有云平台资产
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/Cloud/Account/AccountCreateUpdate.vue
  src/views/assets/Cloud/Account/AccountList.vue
  src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskCreateUpdate.vue
  src/views/assets/Cloud/const.js
Labels: 类型:新功能

#2029 feat: 支持MFA可配置华为云平台短信对接
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/settings/SMS/SMSHuawei.vue
  src/views/settings/SMS/index.vue
Labels: 类型:新功能

#2035 Revert "fix: form表单组件增加是否回显配置；批量更新弹窗组件默认设置为不回显"
  src/layout/components/GenericCreateUpdateForm/index.vue
  src/layout/components/GenericUpdateFormDialog/index.vue
Labels: 类型:bug

#2039 perf: 支持连接开启ssl且自签证书的Redis/MongoDB
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/applications/DatabaseApp/DatabaseAppCreateUpdate.vue
  src/views/applications/DatabaseApp/const.js
Labels: 类型:优化

#2041 fix: 修复数据库创建页面有多个mongodb的问题
  src/views/applications/const.js
Labels: 类型:bug

#2045 perf: 屏蔽--secure参数，目前redis-cli版本为6.0，暂时用不到
  src/views/applications/DatabaseApp/const.js
Labels: 类型:优化

#2067 perf: 修改账号备份表单字段配置
  src/views/accounts/AccountBackupPlan/AccountBackupPlanCreateUpdate.vue
Labels: 类型:优化

#2064 perf: 优化短信配置错误提示不友好问题
  src/views/settings/SMS/Base.vue
  src/views/settings/SMS/CMPP2.vue
  src/views/settings/SMS/SMSAlibaba.vue
  src/views/settings/SMS/SMSHuawei.vue
  src/views/settings/SMS/SMSTencent.vue
Labels: 类型:优化
