Repository jumpserver/lina, pull requests merged in 2022-03, with the labels that each got.

#1356 Revert "fix: 修改资产账号更新回调方法"
  src/components/AccountListTable/index.vue
  vue.config.js
Labels: 类型:bug

#1362 feat: 用户详情tab页rbac控制 (#1359)
  src/views/accounts/AccountBackupPlan/AccountBackupPlanDetail/index.vue
  src/views/accounts/ChangeAuthPlan/index.vue
  src/views/assets/Asset/AssetDetail/index.vue
  src/views/assets/CommandFilter/CommandFilterDetail/index.vue
  src/views/assets/Domain/DomainDetail/index.vue
  src/views/assets/SystemUser/SystemUserList/index.vue
  src/views/ops/TaskDetail/index.vue
  src/views/perms/ApplicationPermission/ApplicationPermissionDetail/index.vue
  src/views/perms/AssetPermission/AssetPermissionDetail/index.vue
  src/views/settings/Terminal/index.vue
  src/views/users/Group/UserGroupDetail/index.vue
  src/views/users/Role/RoleDetail/index.vue
  src/views/users/User/UserDetail/index.vue
Labels: 类型:新功能

#1364 fix: 修复vm的this指针问题
  src/views/users/User/UserDetail/index.vue
Labels: 类型:bug

#1426 fix: 优化权限树(1)
  src/router/audit/index.js
  src/router/console/index.js
  src/router/workspace/index.js
  src/utils/jms.js
  src/views/dashboard/index.vue
  src/views/users/Role/RoleDetail/RoleInfo.vue
Labels: 类型:bug

#1461 perf: 修改 perm 依赖
  src/guards.js
  src/layout/components/NavHeader/index.vue
  src/router/console/accounts.js
  src/router/index.js
  src/router/settings/index.js
  src/utils/startup.js
  src/views/accounts/GatheredUser/TaskList.vue
  src/views/accounts/GatheredUser/index.vue
  src/views/assets/Asset/AssetList.vue
  src/views/users/Role/RoleDetail/RoleInfo.vue
  src/views/users/User/UserDetail/UserInfo.vue
  src/views/users/User/UserDetail/index.vue
Labels: 类型:优化

#1586 feat: 支持纳管百度云资产
  src/i18n/langs/cn.json
  src/i18n/langs/en.json
  src/views/assets/Cloud/Account/AccountList.vue
  src/views/assets/Cloud/const.js
Labels: 类型:新功能

#1616 Revert "perf:: 修复empty组件为函数式组件"
  src/layout/empty.js
  src/layout/empty.vue
  src/router/audit/index.js
  src/router/audit/sessions.js
  src/router/console/accounts.js
  src/router/console/acls.js
  src/router/console/applications.js
  src/router/console/assets.js
  src/router/console/index.js
  src/router/console/ops.js
  src/router/console/perms.js
  src/router/console/sessions.js
  src/router/console/users.js
  src/router/console/xpack.js
  src/router/settings/index.js
  src/router/tickets/index.js
  src/router/workspace/index.js
  src/store/modules/permission.js
Labels: 类型:优化

#1612 feat: 支持日语
  src/i18n/date.js
  src/i18n/i18n.js
  src/i18n/langs/index.js
  src/i18n/langs/ja.json
  src/i18n/langs/removeUnusedKeys.py
  src/layout/components/NavHeader/Language.vue
  src/views/dashboard/ResourceSummary.vue
Labels: 类型:新功能
