Repository jumpserver/lina, pull requests merged in 2022-11, with the labels that each got.

#2125 feat: 云同步支持金山云
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/Cloud/Account/AccountList.vue
  src/views/assets/Cloud/const.js
Labels: 类型:新功能

#2112 feat: 支持纳管 clickhouse[Web Terminal]
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/applications/const.js
  src/views/assets/SystemUser/SystemUserCreateUpdate/CommonUser/index.vue
Labels: 类型:新功能

#2088 feat: 重构操作日志
  src/components/TableFormatters/TwoTabFormatter.vue
  src/components/TableFormatters/index.js
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/audits/OperateLogList.vue
Labels: 类型:新功能

#2144 feat: 显示部分资源的批量删除操作按钮
  src/views/accounts/AccountBackupPlan/AccountBackupPlanList.vue
  src/views/accounts/ChangeAuthPlan/AppChangeAuthPlan/AppChangeAuthPlanList.vue
  src/views/accounts/ChangeAuthPlan/AssetChangeAuthPlan/ChangeAuthPlanList.vue
  src/views/acl/AssetAcl/AssetAclList.vue
  src/views/assets/CommandFilter/CommandFilterList.vue
  src/views/assets/Domain/DomainList.vue
  src/views/assets/Label/LabelList.vue
Labels: 类型:新功能

#2151 perf: update yarn.lock
  yarn.lock
Labels: 类型:优化

#2160 feat: 云资产同步支持选择IP类型
  src/components/TableFormatters/TwoTabFormatter.vue
  src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskCreateUpdate.vue
Labels: 类型:新功能

#2173 Revert "perf: 优化刷新页面方法，避免刷新时页面出现空白"
  src/App.vue
  src/store/modules/common.js
  src/utils/org.js
  src/views/accounts/ChangeAuthPlan/AppChangeAuthPlan/ChangeAuthPlanDetail/ChangeAuthPlanApp/index.vue
  src/views/accounts/ChangeAuthPlan/AssetChangeAuthPlan/ChangeAuthPlanDetail/ChangeAuthPlanAsset/index.vue
  src/views/perms/AssetPermission/AssetPermissionDetail/AssetPermissionAsset.vue
  src/views/sessions/SessionDetail/SessionDetailInfo.vue
  src/views/settings/Interface.vue
  src/views/settings/License.vue
  src/views/tickets/RequestApplicationPerm/Detail/TicketDetail.vue
  src/views/tickets/RequestAssetPerm/Detail/TicketDetail.vue
  src/views/tickets/TicketFlow/Detail/TicketDetail.vue
  src/views/tickets/components/Comments.vue
Labels: 类型:优化

#2168 perf: 优化操作日志界面显示随主题变化
  src/components/TableFormatters/TwoTabFormatter.vue
  src/utils/theme/index.js
  src/views/audits/OperateLogList.vue
Labels: 类型:优化

#2191 fix: 隐藏clickhouse改密入口
  src/views/applications/const.js
Labels: 类型:bug

#2190 fix: 去掉clickhouse改密入口
  src/views/applications/const.js
Labels: 类型:bug

#2198 fix: 解决命令过滤获取不到一些应用的系统用户问题
  src/views/assets/CommandFilter/CommandFilterCreateUpdate.vue
  src/views/assets/CommandFilter/CommandFilterDetail/Detail.vue
Labels: 类型:bug

#2197 fix: 解决命令过滤获取不到一些应用的系统用户问题
  src/views/assets/CommandFilter/CommandFilterCreateUpdate.vue
  src/views/assets/CommandFilter/CommandFilterDetail/Detail.vue
Labels: 类型:bug

#2202 Revert "feat: 切换组织选择器宽度自适应"
  src/layout/components/NavHeader/Organization.vue
Labels: 类型:新功能

#2221 Revert "feat: 仪表盘、工作台默认展开子菜单"
  src/layout/components/NavLeft/index.vue
  src/router/audit/index.js
  src/router/index.js
  src/router/workbench/index.js
Labels: 类型:新功能
