Repository jumpserver/lina, pull requests merged in 2022-08, with the labels that each got.

#1963 feat: 认证方式支持OAuth2.0协议
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/SystemUser/SystemUserCreateUpdate/CommonUser/ssh.vue
  src/views/perms/components/PermissionFormActionField.vue
  src/views/settings/Auth/OAuth2.vue
  src/views/settings/Auth/SAML2.vue
  src/views/settings/Auth/index.vue
Labels: 类型:新功能

#1976 perf: 优化资产树搜索等待时间
  src/components/DataZTree/components/ZTree/index.vue
Labels: 类型:优化

#1985 fix: 资产树默认关闭搜索；调整搜索url携带的参数
  src/components/AssetSelect/index.vue
  src/components/AutoDataZTree/index.vue
  src/components/DataZTree/components/ZTree/index.vue
  src/views/assets/Asset/AssetList.vue
  src/views/ops/CommandExecution.vue
Labels: 类型:bug

#2010 feat: 改密计划支持MongoDB改密
  src/views/applications/const.js
Labels: 类型:新功能

#1997 feat: MongoDB支持连接SSL类型
  src/views/applications/DatabaseApp/DatabaseAppCreateUpdate.vue
  src/views/applications/DatabaseApp/const.js
Labels: 类型:新功能
