Repository jumpserver/lina, pull requests merged in 2023-11, with the labels that each got.

#3489 fix: 解决更新云同步任务时，优先级无法更新问题
  src/views/assets/Cloud/SyncInstanceTask/components/SyncInstanceTaskStrategy/AttrDialog.vue
Labels: 类型:bug

#3533 fix: 云同步任务详情界面删除无用的按钮
  src/views/assets/Cloud/SyncInstanceTask/SyncInstanceTaskDetail/detail.vue
Labels: 类型:bug

#3554 perf: ldap接口请求换成websocket连接
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/settings/Auth/Ldap/ImportDialog.vue
  src/views/settings/Auth/Ldap/TestLoginDialog.vue
  src/views/settings/Auth/Ldap/index.vue
Labels: 类型:优化

#3559 feat: 支持深信服云平台和阿里云专有云
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/Cloud/Account/AccountList.vue
  src/views/assets/Cloud/const.js
Labels: 类型:新功能
