Repository jumpserver/lina, pull requests merged in 2023-04, with the labels that each got.

#2973 feat: Windows类型资产增加winrm协议
  src/components/FormFields/ProtocolSelector/ProtocolSettingDialog.vue
  src/components/FormFields/ProtocolSelector/index.vue
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
Labels: 类型:新功能

#2999 fix: 优化手机号区号更新为空及展示问题
  src/components/FormFields/PhoneInput.vue
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/users/User/UserDetail/UserInfo.vue
Labels: 类型:bug

#3000 fix: 优化手机号区号更新为空及展示问题
  src/components/FormFields/PhoneInput.vue
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/users/User/UserDetail/UserInfo.vue
Labels: 类型:bug

#3002 fix: 解决更新手机号不同步的问题
  src/components/FormFields/PhoneInput.vue
Labels: 类型:bug

#3016 feat: 支持部分资源的自定义自动化任务(Ping/VerifyAccount/ChangeSecret)
  src/components/FormFields/DynamicInput.vue
  src/components/FormFields/index.js
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/Platform/AutomationParamsSetting.vue
  src/views/assets/Platform/PlatformCreateUpdate.vue
  src/views/assets/Platform/PlatformDetail/Automation.vue
  src/views/assets/Platform/const.js
Labels: 类型:新功能

#3041 perf: 优化站内信查看已读逻辑
  src/layout/components/NavHeader/SiteMessages.vue
Labels: 类型:优化

#3077 Revert "perf: 自定义平台协议名称宽度自适应显示"
  src/components/FormFields/ProtocolSelector/index.vue
Labels: 类型:优化
