Repository jumpserver/lina, pull requests merged in 2023-02, with the labels that each got.

#2547 perf: 增加Activity日志中此资源的任务执行及详情查看
  src/components/ResourceActivity/index.vue
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/layout/components/GenericDetailPage/index.vue
  src/router/audit/audits.js
  src/router/audit/index.js
  src/utils/jms.js
  src/views/audits/LoginLogList.vue
  src/views/audits/OperateLog/OperateLogDetail/Detail.vue
  src/views/audits/OperateLog/OperateLogDetail/DetailDialog.vue
  src/views/audits/OperateLog/OperateLogDetail/index.vue
  src/views/audits/OperateLog/OperateLogList.vue
  src/views/audits/components/OperateLogDetail.vue
  src/views/settings/Clean.vue
  src/views/tasks/TaskDetail/index.vue
Labels: 类型:新功能

#2641 perf: 优化Activity日志[操作日志、登录日志]显示
  src/components/Dialog/DiffDetail.vue
  src/components/ResourceActivity/index.vue
  src/router/audit/audits.js
  src/views/audits/LoginLog/LoginLogDetail/Detail.vue
  src/views/audits/LoginLog/LoginLogDetail/index.vue
  src/views/audits/LoginLog/LoginLogList.vue
  src/views/audits/OperateLog/OperateLogDetail/Detail.vue
  src/views/audits/OperateLog/OperateLogList.vue
Labels: 类型:优化

#2663 perf: 修改PostgreSQL数据库参数为必填
  src/views/assets/Asset/AssetCreateUpdate/DatabaseCreateUpdate.vue
Labels: 类型:优化

#2680 Revert "perf：修改svg颜色"
  src/components/SvgIcon/index.vue
  src/icons/svg/accounts.svg
  src/icons/svg/application.svg
  src/icons/svg/arrow-to-left.svg
  src/icons/svg/assets.svg
  src/icons/svg/attestation.svg
  src/icons/svg/audit.svg
  src/icons/svg/basic.svg
  src/icons/svg/broken-line.svg
  src/icons/svg/close.svg
  src/icons/svg/console.svg
  src/icons/svg/create.svg
  src/icons/svg/dashboard.svg
  src/icons/svg/double-left.svg
  src/icons/svg/download.svg
  src/icons/svg/email-fill.svg
  src/icons/svg/email-set.svg
  src/icons/svg/face.svg
  src/icons/svg/file.svg
  src/icons/svg/key.svg
  src/icons/svg/license.svg
  src/icons/svg/list.svg
  src/icons/svg/lock.svg
  src/icons/svg/log.svg
  src/icons/svg/logout.svg
  src/icons/svg/magic.svg
  src/icons/svg/mail.svg
  src/icons/svg/message.svg
  src/icons/svg/my-asset.svg
  src/icons/svg/nav-setting.svg
  src/icons/svg/organization-set.svg
  src/icons/svg/organization.svg
  src/icons/svg/other.svg
  src/icons/svg/overview.svg
  src/icons/svg/permission.svg
  src/icons/svg/personal.svg
  src/icons/svg/refresh.svg
  src/icons/svg/remind.svg
  src/icons/svg/search.svg
  src/icons/svg/security.svg
  src/icons/svg/session.svg
  src/icons/svg/short-message.svg
  src/icons/svg/switch.svg
  src/icons/svg/system-setting.svg
  src/icons/svg/tasks.svg
  src/icons/svg/terminal-set.svg
  src/icons/svg/terminal.svg
  src/icons/svg/ticket-apply.svg
  src/icons/svg/ticket-approval.svg
  src/icons/svg/ticket-flow.svg
  src/icons/svg/ticket-list.svg
  src/icons/svg/token.svg
  src/icons/svg/tools.svg
  src/icons/svg/upload.svg
  src/icons/svg/users.svg
  src/icons/svg/web-terminal.svg
  src/icons/svg/workbench.svg
  src/layout/components/NavHeader/index.vue
  src/layout/components/NavLeft/SidebarItem.vue
  src/styles/index.scss
Labels: 类型:优化

#2681 fix: 点击操作日志详情空白的问题
  src/views/audits/OperateLog/OperateLogDetail/Detail.vue
  src/views/audits/OperateLog/OperateLogList.vue
Labels: 类型:bug

#2682 Revert "Revert "perf：修改svg颜色""
  src/components/SvgIcon/index.vue
  src/icons/svg/accounts.svg
  src/icons/svg/application.svg
  src/icons/svg/arrow-to-left.svg
  src/icons/svg/assets.svg
  src/icons/svg/attestation.svg
  src/icons/svg/audit.svg
  src/icons/svg/basic.svg
  src/icons/svg/broken-line.svg
  src/icons/svg/close.svg
  src/icons/svg/console.svg
  src/icons/svg/create.svg
  src/icons/svg/dashboard.svg
  src/icons/svg/double-left.svg
  src/icons/svg/download.svg
  src/icons/svg/email-fill.svg
  src/icons/svg/email-set.svg
  src/icons/svg/face.svg
  src/icons/svg/file.svg
  src/icons/svg/key.svg
  src/icons/svg/license.svg
  src/icons/svg/list.svg
  src/icons/svg/lock.svg
  src/icons/svg/log.svg
  src/icons/svg/logout.svg
  src/icons/svg/magic.svg
  src/icons/svg/mail.svg
  src/icons/svg/message.svg
  src/icons/svg/my-asset.svg
  src/icons/svg/nav-setting.svg
  src/icons/svg/organization-set.svg
  src/icons/svg/organization.svg
  src/icons/svg/other.svg
  src/icons/svg/overview.svg
  src/icons/svg/permission.svg
  src/icons/svg/personal.svg
  src/icons/svg/refresh.svg
  src/icons/svg/remind.svg
  src/icons/svg/search.svg
  src/icons/svg/security.svg
  src/icons/svg/session.svg
  src/icons/svg/short-message.svg
  src/icons/svg/switch.svg
  src/icons/svg/system-setting.svg
  src/icons/svg/tasks.svg
  src/icons/svg/terminal-set.svg
  src/icons/svg/terminal.svg
  src/icons/svg/ticket-apply.svg
  src/icons/svg/ticket-approval.svg
  src/icons/svg/ticket-flow.svg
  src/icons/svg/ticket-list.svg
  src/icons/svg/token.svg
  src/icons/svg/tools.svg
  src/icons/svg/upload.svg
  src/icons/svg/users.svg
  src/icons/svg/web-terminal.svg
  src/icons/svg/workbench.svg
  src/layout/components/NavHeader/index.vue
  src/layout/components/NavLeft/SidebarItem.vue
  src/styles/index.scss
Labels: 类型:优化

#2687 fix: 解决一些资源的Activity日志无法查看问题
  src/views/sessions/SessionDetail/index.vue
Labels: 类型:bug

#2710 fix: SSL资产克隆无SSL等选项
  src/views/assets/Asset/AssetList/components/BaseList.vue
Labels: 类型:bug

#2807 Revert "perf: lina 提示优化"
  src/components/ListTable/index.vue
  src/i18n/langs/en.json
  src/i18n/langs/ja.json
  src/i18n/langs/zh.json
  src/views/assets/Asset/AssetList/WebList.vue
  src/views/assets/Asset/AssetList/components/BaseList.vue
Labels: 类型:优化
